# Date of the event (UTC-based SPC daily report date)
date: "2011-04-27"

# What to map
event: "tornado"

# Output image name
output_png: "tornado_reports_map.png"

grid_res_deg: 0.25
radius_miles: 25
extent: [-125, -66, 24, 50]
labels_csv: "data/grid_labels.csv"
